### ISSUE TITLE
Docker images: Add support for ARM architectures

### ISSUE THREAD

**Issue by maxromanovsky** [zulu-openjdk/zulu-openjdk#10]
Currently, there are no official ARM docker images for zulu :(

**Comment by gadieichhorn** [comment]
Any idea of how to create an ARM image with Azul @maxromanovsky ?
the official alpine OpenJDK seemed to work on ARM. 

https://github.com/docker-library/openjdk/blob/d93be18f4f2d5e8457169cac00e559d953b6028e/8/jre/alpine/Dockerfile
