### ISSUE TITLE
Alpine 13.0.6 pulls in different JDK build (13.0.7)

### ISSUE THREAD

**Issue by nbaars** [zulu-openjdk/zulu-openjdk#100]
In the Ubuntu version the 13.0.6 image pulls in:

`apt-get -qq -y --no-install-recommends install zulu13-jdk=13.0.6-*`

When pulling the Alpine image:

```
docker pull azul/zulu-openjdk-alpine:13.0.6-13.37.21
```

and asking for the Java version you get:

```
docker run -it azul/zulu-openjdk-alpine:13.0.6-13.37.21 /bin/sh
/ # java -version
openjdk version "13.0.7" 2021-04-20
OpenJDK Runtime Environment Zulu13.40+15-CA (build 13.0.7+5-MTS)
OpenJDK 64-Bit Server VM Zulu13.40+15-CA (build 13.0.7+5-MTS, mixed mode, sharing)
```

The image runs OpenJDK build 13.0.**7** instead of 13.0.**6**.

Seems that the version number of the JDK is not pinned like in Ubuntu, see https://github.com/zulu-openjdk/zulu-openjdk/blob/master/alpine/13.0.6-13.37.21/Dockerfile:

```
apk --no-cache add zulu13-jdk
```

Is this intended?

**Comment by ironstas1k** [comment]
Fixed it, thank you @nbaars
