### ISSUE TITLE
can't run apt-get update on azul image

### ISSUE THREAD

**Issue by andytechdad** [zulu-openjdk/zulu-openjdk#101]
docker run -t docker.io/azul/zulu-openjdk:latest apt-get update

Get:1 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Ign:2 https://repos.azul.com/zulu/deb stable InRelease                                                
Err:3 https://repos.azul.com/zulu/deb stable Release                                                  
  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 13.224.128.40 443]
Get:4 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:5 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]        
Get:6 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]         
Get:7 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]                
Get:8 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:9 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1,418 kB]
Get:10 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [24.7 kB]
Get:11 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [2,221 kB]
Get:12 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Get:13 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1,344 kB]               
Get:14 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [2,656 kB]            
Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [506 kB]
Get:16 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [473 kB]
Get:17 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [33.5 kB] 
Get:18 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [2,188 kB]                                                              
Get:19 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [11.4 kB]                                                             
Get:20 http://archive.ubuntu.com/ubuntu bionic-backports/main amd64 Packages [11.3 kB]                                                                 
Reading package lists... Done                                                                                                                          
E: The repository 'https://repos.azul.com/zulu/deb stable Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Has someone happened witth the cerificiate for your APT repo?

**Comment by andytechdad** [comment]
This looks like our internal network issue.

**Comment by junxy** [comment]
Same Problem `azul/zulu-openjdk:8`
Solved: `rm /etc/apt/sources.list.d/zulu-openjdk.list && apt-get update`
