### ISSUE TITLE
[alpine] broken DNS in alpine images

### ISSUE THREAD

**Issue by rmannibucau** [zulu-openjdk/zulu-openjdk#105]
Hi,

This issue is likely an issue with alpine base image but it affects zulu users so in case you want to include a workaround in the build to give them faster a feedback it would be very appreciated.
Issue is DNS resolution of alpine image is broken since alpine:3.11:

```
rmannibucau@rmannibucau-yupiik:/tmp $ kubectl run -ti --rm alpine --image=alpine:3.11 --restart=Never -- nslookup ewib.nbp.pl
Server:		172.30.0.10
Address:	172.30.0.10:53

Non-authoritative answer:
Name:	ewib.nbp.pl
Address: 195.85.196.98
Name:	ewib.nbp.pl
Address: 193.109.212.98

** server can't find ewib.nbp.pl: NXDOMAIN

pod "alpine" deleted
pod tppwise/alpine terminated (Error)
rmannibucau@rmannibucau-yupiik:/tmp $ kubectl run -ti --rm alpine --image=alpine:3.10 --restart=Never -- nslookup ewib.nbp.pl
nslookup: can't resolve '(null)': Name does not resolve

Name:      ewib.nbp.pl
Address 1: 195.85.196.98
Address 2: 193.109.212.98
pod "alpine" deleted
```

Since zulu uses alpine:3.13 it is affected.
I'm not sure the best way to solve it (there are a lot of options over the net, like replacing the kernel etc) but having a base image ~70M and not 100M is really good for end users and reduce latency when working with k8s so would be great to have new alpine images with a fix for that.

side note: if you read about the ndots workaround, it does NOT work ;).

Romain

**Comment by ironstas1k** [comment]
Hi @rmannibucau,

We'v successfully bumped latest Zulu alpine release to 3.14, does it solves your issue? 

- Stas

**Comment by rmannibucau** [comment]
Hi @ironstas1k,

Fetch `azul/zulu-openjdk-alpine:16.0.2-16.32.15-jre@sha256:d323c348f27b9458ec88fd69947560314df0fe059ff7acb3055f96b28f466a4d` and didn't get the issue so I think this can be closed.

**Comment by rmannibucau** [comment]
For the story, in kubernetes it can fail again and `-Djava.net.preferIPv4Stack=true` solves it.
