### ISSUE TITLE
openjdk docker image for Java 17

### ISSUE THREAD

**Issue by vivekmalhotragithub** [zulu-openjdk/zulu-openjdk#108]
When can we expect a JDK 17 image?

**Comment by gesundes** [comment]
Hi there,

JDK 17 Docker images were released yesterday. Here is a link to the page with all available images: https://hub.docker.com/u/azul

A list of tags for one of the images: https://hub.docker.com/r/azul/zulu-openjdk/tags?page=1&ordering=last_updated

Dockerfiles were updated today.
