### ISSUE TITLE
ELF interpreter should be /lib/ld-linux-aarch64.so.1 instead of /lib64/ld-linux-aarch64.so.1 on Ubuntu LTS 16.04 for aarch64

### ISSUE THREAD

**Issue by baiyz** [zulu-openjdk/zulu-openjdk#11]
**Ubuntu 16.04.3 LTS**
root@1p-1: # uname -a
Linux 1p-1 4.12.0-12-generic #13 SMP Tue Aug 22 11:58:51 CDT 2017 aarch64 aarch64 aarch64 GNU/Linux

root@1p-1: # cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"

**Zulu JDK on arm64**
root@1p-1:/usr/lib/jvm/ezdk-1.8.0_131-8.21.0.54-eval-linux_aarch64/jre/bin# ./java -version
-su: ./java: No such file or directory

root@1p-1:/usr/lib/jvm/ezdk-1.8.0_131-8.21.0.54-eval-linux_aarch64/jre/bin# file java
java: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-aarch64.so.1, for GNU/Linux 3.14.0, BuildID[sha1]=fda8e0f16e1d88ac257c444577f625493041ac96, stripped

**Oracle JDK on arm64**
root@1p-1:/usr/lib/jvm/java-8-oracle/jre/bin# ./java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

root@1p-1:/usr/lib/jvm/java-8-oracle/jre/bin# file java
java: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=840c10934b96bca53acdcaf04979d5bdec021318, not stripped

**Comment by baiyz** [comment]
According to http://www.pathname.com/fhs/pub/fhs-2.3.html#LIBLTQUALGTALTERNATEFORMATESSENTIAL, /lib64 should be optional

**Comment by sgrinev** [comment]
Closing, as this github is only about Zulu Enterprise Community docker builds. 
I've forwarded your issue to the ARM platform Zulu Embedded team.
