### ISSUE TITLE
jaotc not included in M1 JDK15/JDK16 aarch64

### ISSUE THREAD

**Issue by dvcrn** [zulu-openjdk/zulu-openjdk#117]
Noticed the jaotc bin is missing in the JDK15/16 aarch64

aarch64: 

<img width="1022" alt="Screen Shot 2021-11-30 at 14 36 24" src="https://user-images.githubusercontent.com/688326/143991840-e222e4ed-629e-4755-a967-cbceb069fff7.png">

x86_64:

<img width="1022" alt="Screen Shot 2021-11-30 at 14 35 52" src="https://user-images.githubusercontent.com/688326/143991922-c0033339-37fd-4b20-8d46-6cd631e7100b.png">

Is this supposed to be included on aarch64 builds?

**Comment by AntonKozlov** [comment]
Hi! The AOT functionality is intentionally disabled in macos/aarch64 bundles as it is known to have issues. AOT was removed from JDK 17, so we decided not to implement it in older major versions. Right now, we don't have any plans to implement AOT in 15 and 16.

**Comment by dvcrn** [comment]
Thanks for clarifying! I didn't know that
