### ISSUE TITLE
`zulu-openjdk-alpine:17.0.2` contains 17.0.0 instead of 17.0.2

### ISSUE THREAD

**Issue by famod** [zulu-openjdk/zulu-openjdk#121]
Not sure this is the right repo to report that, but this doesn't look right:
```
$ docker run --rm azul/zulu-openjdk-alpine:17.0.2 java -version
openjdk version "17" 2021-09-14 LTS
OpenJDK Runtime Environment Zulu17.28+13-CA (build 17+35-LTS)
OpenJDK 64-Bit Server VM Zulu17.28+13-CA (build 17+35-LTS, mixed mode, sharing)
```
compared with:
```
$ docker run --rm azul/zulu-openjdk-alpine:17.0.1 java -version
openjdk version "17.0.1" 2021-10-19 LTS
OpenJDK Runtime Environment Zulu17.30+15-CA (build 17.0.1+12-LTS)
OpenJDK 64-Bit Server VM Zulu17.30+15-CA (build 17.0.1+12-LTS, mixed mode, sharing)
```

So it looks like 17.0.2 is back to 17.0.0 (so to say)?

**Comment by famod** [comment]
The Ubuntu image looks ok:
```
$ docker run --rm azul/zulu-openjdk:17.0.2 java -version
openjdk version "17.0.2" 2022-01-18 LTS
OpenJDK Runtime Environment Zulu17.32+13-CA (build 17.0.2+8-LTS)
OpenJDK 64-Bit Server VM Zulu17.32+13-CA (build 17.0.2+8-LTS, mixed mode, sharing)
```

**Comment by ironstas1k** [comment]
Hey @famod,
Thank you for catching it so fast.
Unfortunately our automation missed that 17.0.2 packages weren't released yet to Alpine repos and we accidentally pushed wrong images, now it's fixed.
17.0.2 should be back till end of this/first half of next week and we are also going to release arm64 as well.

**Comment by famod** [comment]
Thanks @sgrinev for your very fast feedback! I'll check later then.

I have no clue how your automation/CI looks like, but maybe you could add a sanity check (e.g. grep the output of `java -version` or so).

**Comment by famod** [comment]
Hi @ironstas1k @sgrinev, any news?
Still nothing to see here: https://hub.docker.com/r/azul/zulu-openjdk-alpine/tags?page=1&name=17.0.2
Thanks!

**Comment by cmuchinsky** [comment]
@famod I just happened to notice that the `17.0.2` images were published a few hours ago
