### ISSUE TITLE
It looks like something changed on your infra that now zulu6, zulu7, zulu9 could not be installed through apt-get

### ISSUE THREAD

**Issue by bashor** [zulu-openjdk/zulu-openjdk#124]
So, relevant Dockerfiles are broken now, e.g. these ones:
https://github.com/zulu-openjdk/zulu-openjdk/blob/master/6u119-6.22.0.3/Dockerfile
https://github.com/zulu-openjdk/zulu-openjdk/blob/master/7u322-7.50.0.11/Dockerfile
https://github.com/zulu-openjdk/zulu-openjdk/blob/master/9u07-9.0.7.1/Dockerfile

**Comment by it-mak** [comment]
It was temporary internal problems.
