### ISSUE TITLE
Why apt-get, and not apk?

### ISSUE THREAD

**Issue by demaniak** [zulu-openjdk/zulu-openjdk#13]
Just a question: why use apt-get (in at least azul/zulu-openjdk-alpine:8u144, not sure about earlier) and not apk (which afaik is the "normal" package manager for alpine) ?

Apologies if this is the wrong repo! I got the link from [docker hub](https://hub.docker.com/r/azul/zulu-openjdk-alpine/)

**Comment by sgrinev** [comment]
We had a bug in 8u144 alpine build which was just recently fixed. The current alpine image is based on https://github.com/zulu-openjdk/zulu-openjdk/blob/master/alpine/8u144-8.23.0.3/Dockerfile and uses apk. Redownload image, or use "8-latest" tag which had no issues.

**Comment by demaniak** [comment]
great, thanks @sgrinev , I will try that now.

**Comment by demaniak** [comment]
Thanks much, looks good!
