### ISSUE TITLE
setlocale: LC_ALL: cannot change locale (en_US.UTF-8)

### ISSUE THREAD

**Issue by sanyer** [zulu-openjdk/zulu-openjdk#130]
Using image `azul/zulu-openjdk-debian:8u322-8.60.0.21` results in this message in docker logs:

```
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
```

Not sure why is this happening. Dealing with locales on debian was always a magic to me.
Any suggestions?

**Comment by ironstas1k** [comment]
Hey @sanyer,

Thank you, we've added your fix to our dockerfile templates.
Appreciate your help!

**Comment by sanyer** [comment]
Thanks @ironstas1k , glad to help :-)
