### ISSUE TITLE
Many of the alpine 17.0.1 JDK docker images are arm64 built and does not work on linux machines

### ISSUE THREAD

**Issue by fatihdogmus** [zulu-openjdk/zulu-openjdk#132]
Hello,

Today, we realized that our application wasn't starting up. And was giving a very weird error like this on our demo environment:

WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64) and no specific platform was requested
standard_init_linux.go:228: exec user process caused: exec format error

We were really confused, since we didn't change anything over the weekend, and it was working before we headed out for weekend. We have a CD pipeline that deploys our application at the end of each day to our demo environment. And it broke today.

Turns out, there was a push to the tag that we are using, 17.0.1-jre, that turned it into a linux/arm64/v8 architecture image instead of linux/amd64.
![image](https://user-images.githubusercontent.com/16986743/158200932-f40a7573-f3cb-47e4-9f57-a8d73de6696e.png)
In fact, most of the 17.0.1 images are now arm64 based.

Fortunately, we have not deployed to production yet, but this could have been really bad.

When we switched to a temurin image, application started out without a problem.

**Comment by sgrinev** [comment]
Thanks for reporting, we'll look at it ASAP.

**Comment by ironstas1k** [comment]
Hello @fatihdogmus, 
Unfortunately, due to mistake, our weekly release process accidentally started on arm64 VMs and we didn't catch it during weekend.
This mistake was fixed and we've added improvements to this process.
Sorry for that and appreciate your choice for Zulu docker images.
