### ISSUE TITLE
Zulu Ubuntu Images do not Get Regular Security Fixes from Base Image

### ISSUE THREAD

**Issue by Akaame** [zulu-openjdk/zulu-openjdk#133]
After pulling `azul/zulu-openjdk:17` that has the Ubuntu base image, our vulnerability scan alerted that this image has several high/medium level vulnerabilities. `apt-get update && apt-get upgrade` cleans this up. 

What is the policy regarding security updates for Zulu images? How often are these being rebuilt incorporating security fixes? 

Cheers.

**Comment by ironstas1k** [comment]
Hey @Akaame,

This issue should be resolved cause we fixed our weekly update process. The images should pick new security changes every Friday. 

Thanks!
