### ISSUE TITLE
Zulu OpenJDK Alpine dependencies are outdated

### ISSUE THREAD

**Issue by Akaame** [zulu-openjdk/zulu-openjdk#143]
[This](https://github.com/zulu-openjdk/zulu-openjdk/blob/0448b86be4c9f16004a92b4de2210ae8f69736f6/alpine/17.0.2-17.32.13/Dockerfile_x86) shows me that Alpine images are based on Alpine 3.14. Current zulu-openjdk-17 and zulu-openjdk-11 images are vulnerable and they are needed to be updated to Alpine 3.14.6. Since this is a patch version bump-up a rebuild should be enough. For Ubuntu based images there is a pipeline that runs every Friday and keeps the image up-to-date with the changes from the base (see #133). What is the strategy for Alpine images?

One problem Alpine bases have is this [vuln](https://security.snyk.io/vuln/SNYK-ALPINE314-BUSYBOX-2440608).

Thanks in advance for your help and cheers.

**Comment by ironstas1k** [comment]
Hey @Akaame,

As far as I can see your link is pointed to the outdated commit which was based on Alpine 3.14, but [it's not anymore. ](https://github.com/zulu-openjdk/zulu-openjdk/blob/master/alpine/17.0.2-17.32.13/Dockerfile_x86)

```
~|⇒ podman pull azul/zulu-openjdk-alpine:17
Resolving "azul/zulu-openjdk-alpine" using unqualified-search registries (/etc/containers/registries.conf.d/999-podman-machine.conf)
Trying to pull docker.io/azul/zulu-openjdk-alpine:17...
Getting image source signatures
Copying blob sha256:4da57c63be2bcb86cc7d76934e540ca2dabad3254fd38c264cc0fb3a22c42326
Copying blob sha256:df9b9388f04ad6279a7410b85cedfdcb2208c0a003da7ab5613af71079148139
Copying blob sha256:4da57c63be2bcb86cc7d76934e540ca2dabad3254fd38c264cc0fb3a22c42326
Copying config sha256:bb10c790e44aa2f57f2b8087200a16ba84d68af6a0473d08b33db3868ed3a032
Writing manifest to image destination
Storing signatures
bb10c790e44aa2f57f2b8087200a16ba84d68af6a0473d08b33db3868ed3a032
~|⇒ podman run -it --rm azul/zulu-openjdk-alpine:17 cat /etc/issue
Welcome to Alpine Linux 3.15
Kernel \r on an \m (\l)
```

Could you please provide exact image tags from january release which are still based on Alpine 3.14?

**Comment by Akaame** [comment]
Sorry, I do not know how I ended up in the specific commit but taking everything atop I see that indeed on branch master it is 3.15 and both distributed images `azul/zulu-openjdk-alpine:17` and `azul/zulu-openjdk-alpine:11` are on Alpine 3.15.4 therefore safe from the mentioned vulnerability. Sorry for the inconvenience. I am closing this as it is a non-issue.
