### ISSUE TITLE
Missing JDK 17.0.3 Release

### ISSUE THREAD

**Issue by henrysachs** [zulu-openjdk/zulu-openjdk#144]
Hey There, 

I'm currently trying to update the java runtime for "Psychic Signature" and noticed that the alpine images still use the 

```
openjdk 17.0.2 2022-01-18 LTS
OpenJDK Runtime Environment Zulu17.32+13-CA (build 17.0.2+8-LTS)
OpenJDK 64-Bit Server VM Zulu17.32+13-CA (build 17.0.2+8-LTS, mixed mode, sharing)
```

which is marked as vulnerable. As I saw that there is already a fixed version from AZUL when will these reach the docker images? 
I noticed that the apk repo also still downloads 17.0.2

This is the fix I found:

https://www.azul.com/downloads/?version=java-17-lts&os=alpine-linux&package=jdk

**Comment by johanhammar** [comment]
While not vulnerable for "Psychic Signature", we're also missing other updated Java images, i.e 8.0.332 and 11.0.15

**Comment by chulkilee** [comment]
There are several 17.0.3 images available (updated yesterday) - but README (thus docker hub description) says 17.0.2 is the latest. Seems like this repo does not have the commit related to the pushed image. 🤦 

https://hub.docker.com/r/azul/zulu-openjdk/tags?page=1&name=17.0.3

**Comment by it-mak** [comment]
For now latest version is 17.0.4
