### ISSUE TITLE
Only arm64 arch available for 17.0.2-jre image on docker hub

### ISSUE THREAD

**Issue by steve-r-west** [zulu-openjdk/zulu-openjdk#145]
Hi,
It seems that the 17.0.2-jre image is only available for arm64 and not amd64 which causes errors on our ci machines when we are buling our application images.

This is similar to a previous issue #142 which itself was similar to a previous issue #132 

My read of #142 says this should have been resolved during the weekly builds, but the most recent ones as of today yesterday still have this issue.

![image](https://user-images.githubusercontent.com/49958178/164541790-15bf4f23-9d23-4de4-99ae-8cb022b8c762.png)

https://hub.docker.com/r/azul/zulu-openjdk-centos/tags?page=1&name=17.0.2-jre-headless

**Comment by it-mak** [comment]
For now 17.0.2-jre is multiplatform
