### ISSUE TITLE
Add missing intermediate CA for www.adm.gov.it

### ISSUE THREAD

**Issue by irizzant** [zulu-openjdk/zulu-openjdk#147]
Hello
from inside Azul JDK Zulu 8.62.0.19-CA-linux64 docker image if I run:
`openssl s_client -verify 100 -showcerts -connect www.adm.gov.it:443 -CAfile  <(keytool -list -rfc -keystore cacerts -storepass xxxx)`

I get a SSL error because the intermediate certificate is missing:
[Actalis Organization Validated Server CA G3.tar.gz](https://github.com/zulu-openjdk/zulu-openjdk/files/8609919/Actalis.Organization.Validated.Server.CA.G3.tar.gz)

Is it possible to add it to the image?

**Comment by it-mak** [comment]
We already have root certificate, it's:
Actalis S.p.A | Actalis Authentication Root CA 
We don't include any additional intermediate certificates.
