### ISSUE TITLE
Alpine version of JDK9 is missing

### ISSUE THREAD

**Issue by PennyYip** [zulu-openjdk/zulu-openjdk#15]
Ubuntu version is available but alpine is missing, please add the alpine version.

**Comment by CamW** [comment]
Seems like alpine version is missing for the newly released version 10 too. I'm assuming this is related to glibc? Would you consider PRs for this or have you decided to stop providing an official alpine container?

**Comment by sgrinev** [comment]
Currently zulu9&10 builds are not compatible with glibc-alpine we are using for previous zulu versions. Engs are looking into but there is no ETA right now.

**Comment by rufoa** [comment]
The solution I've found (tested with Zulu 10) is to copy some libs from arch:

Download https://www.archlinux.org/packages/core/x86_64/gcc-libs/download
Extract `usr/lib/libgcc_s.so*` and `usr/lib/libstdc++.so*` to `/usr/glibc-compat/lib/`
Download https://www.archlinux.org/packages/core/x86_64/zlib/download
Extract `usr/lib/libz.so*` to `/usr/glibc-compat/lib/`

If this is a satisfactory solution in your eyes, I'd be happy to make a PR

**Comment by rufoa** [comment]
https://github.com/zulu-openjdk/zulu-openjdk/pull/23
