### ISSUE TITLE
Zulu JDK 11.0.15:  -XX:+UseOpenJSSE not recognized

### ISSUE THREAD

**Issue by laiddlai** [zulu-openjdk/zulu-openjdk#151]
The option -XX:+UseOpenJSSE no longer works in 11.0.15. 

With Zulu 11.0.15 (fails):

$ java -XX:+UseOpenJSSE
Unrecognized VM option 'UseOpenJSSE'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
$ java -version
openjdk version "11.0.15" 2022-04-19 LTS
OpenJDK Runtime Environment Zulu11.56+19-CA (build 11.0.15+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.56+19-CA (build 11.0.15+10-LTS, mixed mode)

With Zulu 11.0.9 (works, no complaint about the option):

$ java -XX:+UseOpenJSSE
Usage: java [options] <mainclass> [args...]
           (to execute a class)
$ java -version
openjdk version "11.0.9.1" 2020-11-04 LTS
OpenJDK Runtime Environment Zulu11.43+55-CA (build 11.0.9.1+1-LTS)
OpenJDK 64-Bit Server VM Zulu11.43+55-CA (build 11.0.9.1+1-LTS, mixed mode)
This looks to be a regression of Zulu JDK.

**Comment by sgrinev** [comment]
Hi @laiddlai.

We removed OpenJSSE from zulu11 since January 2022 release. Please, see more details here: https://docs.azul.com/core/zulu-openjdk/release-notes/january-2022#openjsse-removed-from-azul-zulu-11
