### ISSUE TITLE
Container README is confusing because it points to «11-latest» images and they do not exist

### ISSUE THREAD

**Issue by prullanferragut** [zulu-openjdk/zulu-openjdk#153]
Container README is confusing because it points to «11-latest» images and they do not exist.

In the main page it references to «Tags and Dockerfile links - Most Recent» but the «11-latest» tag for example does not exist.

I would recommend creating the «xversion-latest» tag for all versions to avoid confusion.

![image](https://user-images.githubusercontent.com/86043499/180201579-1305fadc-2ff1-43ff-86b8-c9e56758aec6.png)

https://hub.docker.com/r/azul/zulu-openjdk/tags?page=1&name=latest
![image](https://user-images.githubusercontent.com/86043499/180201640-1a2bbd87-09aa-4c99-8f8d-f6c50752818a.png)

**Comment by thirdgen88** [comment]
Same applies for `17-latest` tags, FYI.

**Comment by it-mak** [comment]
Thank you for request. Has been implemented for 11,17,18-jdk, other versions will come in further updates.
