### ISSUE TITLE
wrong architecture for recently pushed docker containers

### ISSUE THREAD

**Issue by deltamualpha** [zulu-openjdk/zulu-openjdk#154]
```
# docker run -it azul/zulu-openjdk-alpine:17.0.4-jre bash
Unable to find image 'azul/zulu-openjdk-alpine:17.0.4-jre' locally
17.0.4-jre: Pulling from azul/zulu-openjdk-alpine
e0295fd11fe2: Pull complete
9985721d8dde: Pull complete
Digest: sha256:4a2f9889ff7ec21da049b60d030f23371055332fd15420e0ab6b67752f36c5fb
Status: Downloaded newer image for azul/zulu-openjdk-alpine:17.0.4-jre
WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested
docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "bash": executable file not found in $PATH: unknown.
# arch
i386
```

Not sure what's going on here, but I'm seeing all sorts of issues pulling images on x64 platforms and getting ARM versions of the docker image, both on my local Intel mac and in my CI environment.

Related issues appear to be #132, #142, #145. #152 appears to be the opposite problem?

At this rate we're going to have to switch away from zulu if consistent docker issues like this keep coming up.

**Comment by nineinchnick** [comment]
I also noticed a similar issue in the workflow runs of the Trino project: https://github.com/trinodb/trino

**Comment by deltamualpha** [comment]
@ironstas1k are you the right person to ping about this?

**Comment by mickroll** [comment]
See also https://github.com/zulu-openjdk/zulu-openjdk/issues/155#issuecomment-1197837537

**Comment by it-mak** [comment]
17.0.4-jre is multiarch already
