### ISSUE TITLE
17.0.4-jre-headless broken since July 27th?

### ISSUE THREAD

**Issue by famod** [zulu-openjdk/zulu-openjdk#155]
Preface: Not sure this is the right place to report this, given that this repo does not even have a 17.0.4 folder yet.

Yesterday, we started getting the following errors trying to start or containers as usual: `exec format error`
There have been image updates over the course of the day, but for us the error prevails.

Strangely, on my local machine I was not seeing this issue but I had massive cpu load each time I tried starting of our containers via docker-compose.

All those issues went away after pinning the base image to `azul/zulu-openjdk-alpine@sha256:254ca64ceace793f3e14ad88504b6c847e611f2f9fe72308ff3a1f6c73a16c77`, which is the last working version we could find when analyzing our Jenkins build logs.

**Comment by mickroll** [comment]
17.0.3-jre-headless is available for both arm64 and amd64: https://hub.docker.com/layers/zulu-openjdk-alpine/azul/zulu-openjdk-alpine/17.0.3-jre-headless/images/sha256-bfa5f70358048ea48ad5e86e57321e52efe4fdfae9da1caf3f83c7ed31613532?context=explore
17.0.4-jre-headless is only available for arm64: https://hub.docker.com/layers/zulu-openjdk-alpine/azul/zulu-openjdk-alpine/17.0.4-jre-headless/images/sha256-8fd2cb77368abb32f7d808a06a5e3074cab0ad8bf914ec383a1b09a96609cd0f?context=explore
(in fact, most of 17.0.4 seem to only be available for arm64)

*scratching head* but why does docker even _try_ to use the image for the wrong architecture!?

**Comment by famod** [comment]
It's really weird to have an arch disappear for a floating tag that not even references only a major version (but a patch version).

**Comment by it-mak** [comment]
Latest manifests are multiarch, it's better to use common tags.
