### ISSUE TITLE
images for azul/zulu-openjdk on docker hub with tags 17.0.4-jre and 17.0.4-jre-headless with SAME SIZE

### ISSUE THREAD

**Issue by pmerson** [zulu-openjdk/zulu-openjdk#160]
The [image for tag 17.0.4-jre](https://hub.docker.com/layers/azul/zulu-openjdk/17.0.4-jre/images/sha256-fa30180b759976f5f3b795443616f23158b2fe96540ff9fd8161dd223a8ec1ce?context=explore) shows:

 - compressed size 170.02 MB
 - DIGEST:sha256:fa30180b759976f5f3b795443616f23158b2fe96540ff9fd8161dd223a8ec1ce

The [image for tag 17.4.4-jre headless](https://hub.docker.com/layers/azul/zulu-openjdk/17.0.4-jre-headless/images/sha256-fa30180b759976f5f3b795443616f23158b2fe96540ff9fd8161dd223a8ec1ce?context=explore) **also** shows:
- compressed size 170.02 MB
- DIGEST:sha256:fa30180b759976f5f3b795443616f23158b2fe96540ff9fd8161dd223a8ec1ce

I imagine it's a `build`/`tag` issue since the headless version is supposed to be smaller.

**Comment by it-mak** [comment]
We have removed unnecessary packages.
