### ISSUE TITLE
11-jre Build Removes Necessary Linux Common Libraries

### ISSUE THREAD

**Issue by jclausen** [zulu-openjdk/zulu-openjdk#163]
The [usage of `apt autoremove` in your JRE Dockerfiles](https://github.com/zulu-openjdk/zulu-openjdk/blob/master/11-jre-headless-latest/Dockerfile#L19) is removing common Linux binaries like `ps`.

The base focal image , for example, has this command available, but the final build Azul JRE image does not:

```
# Base focal image contains the `ps` binary
docker run --rm -it ubuntu:focal ps -p 123
  PID TTY          TIME CMD

# Built Azul image no longer has `ps` 
docker run -it --rm azul/zulu-openjdk-debian:11-jre-headless ps -p 123
docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "ps": executable file not found in $PATH: unknown.
```

**Comment by it-mak** [comment]
It's not a bug, we use debian-slim images. The right dockerfile is https://github.com/zulu-openjdk/zulu-openjdk/blob/master/debian/11-jre-latest/Dockerfile 

```
docker run -it debian:bullseye-slim bash
root@a400302617f2:/# ps
bash: ps: command not found
```
You can use our Ubuntu based image or customize Debian based according your needs.
