### ISSUE TITLE
Remove Build Tools and Clean Cache

### ISSUE THREAD

**Issue by vjkoskela** [zulu-openjdk/zulu-openjdk#18]
The docker image build installs `wget` as part of the Zulu JDK installation process.

e.g.
https://github.com/zulu-openjdk/zulu-openjdk/blob/master/alpine/8u162-8.27.0.7/Dockerfile

In my opinion, any such build tools (e.g. not required at container runtime) should be removed at the end of the image build (e.g. `apk del`). Further, the apk package cache should also be cleared (e.g. `rm -rf /var/cache/apk/*`). This will restore the alpine image back to its base set of tools and minimum footprint (with the exception of the Zulu JDK).

**Comment by sgrinev** [comment]
Do you care enough to provide a pull request? :)

**Comment by vjkoskela** [comment]
I modified only the latest Alpine JDK8 definition.
