### ISSUE TITLE
Missing libraries to support EC cryptography in Azul Zulu OpenJDK needed for OWASP dependency check task

### ISSUE THREAD

**Issue by jmptk** [zulu-openjdk/zulu-openjdk#183]
Hi, 
we are using in our Azure DevOps pipeline OWASP Dependency Check task that needs either OracleJDK or OpenJDK (our case) and suddenly all pipelines that use it, throwed error. **We used** older version of **Azul Zulu: 11** (don't remember specific number) but after this error **I updated** it to latest **Azul Zulu: 11.62.17** for Windows, still with no success.

In log was stated:
[ERROR] Unable to continue dependency-check analysis.
[ERROR] One or more fatal errors occurred
[ERROR] org.owasp.dependencycheck.utils.DownloadFailedException: TLS Connection Reset
Please see http://jeremylong.github.io/DependencyCheck/data/tlsfailure.html for more information regarding how to resolve the issue.
[ERROR] No documents exist

I checked the link in the error message https://jeremylong.github.io/DependencyCheck/data/tlsfailure.html, and it stated: 
_"In some installations of the JRE (such as OpenJDK on CentOS/RHEL/Amazon Linux) do not have the correct libraries to support EC cryptography. If you run into problems running dependency-check you may need to install Bouncy Castle and configure Java to use the more robust cryptographic provider."_

I did all the steps to add BouncyCastle provider to our Azul Zulu OpenJDK but it still does not work. 

It seems like the OWASP maybe did some change in their requirements and now the Zulu OpenJDK libraries are not enough, even though up until now, it worked fine.

**My question is:** is it possible that Azul Zulu OpenJDK is missing some cryptography libraries that will be added in time? Do you know about this issue and plan any update of your libraries to support these ECs? 

Thank you in advance and best regards

**Comment by it-mak** [comment]
Thank you, we'll take a look closer at this issue.

**Comment by alexeybakhtin** [comment]
Hello, 
Azul Zulu 11.62.17 for Windows is provided with all necessary EC crypto algorithms required for TLS connection. It could be some other TLS connection problem, e.g. firewall is enabled/reconfigured on your system. Could you please collect TLS connection logs from Zulu11? It could be done with “-Djavax.net.debug=ssl,handshake” option.
Thank you

**Comment by jmptk** [comment]
Hi guys, 

first of all, thanks for reply.

For @alexeybakhtin , this is what I tried in PowerShell. Am I in right folder?

PS C:\Program Files\Zulu\zulu-11\bin> java -Djavax.net.debug=ssl,handshake
Error: Could not find or load main class .net.debug=ssl,handshake
Caused by: java.lang.ClassNotFoundException: /net/debug=ssl,handshake

**Comment by jmptk** [comment]
Hi @alexeybakhtin,

Maybe I should have specified that our code is in C# and I am not familiar with Java. So should it be set in variables of the pipeline? Or executed in script? I cannot find anything close to MAVEN_OPTS variable for Azure Devops to be used in pipeline. But I will keep looking and let you know.  

Also to regard your first answer, I will double check the the firewall configuration with responsible team.

**Comment by jmptk** [comment]
Hi @alexeybakhtin, @it-mak 

problem was in blocked website www.cisa.gov, which seems to provide CVEs (common vulnerabilities and exposures) to OWASP dependency check, so OWASP is then able to compare it and post results. Everything works fine on OpenJDK Azul Zulu: 11.62.17, **without** adding BouncyCastle as a provider. 

This issue can be closed.

Thank you for your time and help.
