### ISSUE TITLE
https://repos.azul.com/zulu/alpine/ returns HTTP 403

### ISSUE THREAD

**Issue by cowwoc** [zulu-openjdk/zulu-openjdk#187]
The instructions at https://docs.azul.com/core/zulu-openjdk/install/alpine-linux ask users to invoke:

> echo "https://repos.azul.com/zulu/alpine" | sudo tee -a /etc/apk/repositories

but (at the time this issue was filed) https://repos.azul.com/zulu/alpine returns HTTP 403 without an explanation.

**Comment by it-mak** [comment]
Thank you for the request regarding the 403 error you encountered. I would like to assure you that this error is expected and is not a cause for concern. The instructions are right, i just checked alpine installation by the steps. Packets and index accessible via other url, as example https://repos.azul.com/zulu/alpine/x86_64/APKINDEX.tar.gz
