### ISSUE TITLE
Multi-architecture image for JDK 11 + Alpine

### ISSUE THREAD

**Issue by georgew5656** [zulu-openjdk/zulu-openjdk#188]
**Problem**
Both ubuntu and alpine distros have support for multiarchitecture images, but for ubuntu, arm support is done through a multi architecture image, whereas for alpine arm support is done through a second tag. This makes it harder to build multi architecture images based on the azul alpine base image.

ubuntu: https://hub.docker.com/layers/azul/zulu-openjdk/11.0.16.1/images/sha256-e1ccb660c16c6ce371317f8bcdd11007714182fd84cf4ced56da0e6b28772257?context=explore

alpine: https://hub.docker.com/layers/azul/zulu-openjdk-alpine/11.0.18-11.62.17-arm64/images/sha256-0d600b7f7494eddf2da84d9e61aa5c5ad736c4e559bfc8dd175361df714a31a2?context=explore

the jdk 17 + alpine image does seem to support multiarchitecture https://hub.docker.com/layers/azul/zulu-openjdk-alpine/17.0.5-17.38.21/images/sha256-81959901fb399c3c6af7e97aa2a954d25d7bb027a394dbbc4e094549bb57d801?context=explore

**Solution Proposal**
Ideally the alpine image would support a multiarchitecture image for jdk 11 rather than two separate images

**Comment by it-mak** [comment]
Thank you for your feedback. We have the same approach for all of our images. 
The problem has been fixed. In this case, it was the new arm64 alpine version, and the issue was due to a missed weekly update for a particular version tag. I apologize for any inconvenience this may have caused.

**Comment by georgew5656** [comment]
thank you!

an unrelated question, but I noticed that arm is only supported starting in 11.0.18 (e.g. 11.0.16 alpine has no arm support) I assume that was intentional?
