### ISSUE TITLE
License of Dockerfiles

### ISSUE THREAD

**Issue by bennypi** [zulu-openjdk/zulu-openjdk#20]
Hi, 
can you specify the copyright statement and under which license the dockerfiles are released?

Furthermore, 
1. Am I allowed to make changes to a dockerfile and then host the dockerfile in another repository on github with a statement that I used a Dockerfile from this repository as a base?
2. Am I allowed to host the resulting docker image publicly available on another repository, e.g. JFrog bintray or dockerhub?

**Comment by sgrinev** [comment]
The copyright statement is in progress, but for both other questions the answer is "Yes, absolutely" :)

**Comment by bennypi** [comment]
Awesome, thanks!
