### ISSUE TITLE
JAVA_HOME is not defined correctly in most recent azul/zulu-openjdk:19 docker images for arm64 platform

### ISSUE THREAD

**Issue by BranislavBeno** [zulu-openjdk/zulu-openjdk#200]
Usage of most recent `azul/zulu-openjdk:19` docker images for arm64 platform ends with error message:
> Error: JAVA_HOME is not defined correctly.
>  We cannot execute /usr/lib/jvm/zulu19-ca-amd64/bin/java

While previous docker images, e.g. `azul/zulu-openjdk:19.0.1` have set `JAVA_HOME` to **/usr/lib/jvm/zulu19-ca-arm64**,
the most recent docker images, e.g. `azul/zulu-openjdk:19.0.2` have set `JAVA_HOME` to **/usr/lib/jvm/zulu19-ca-amd64**.

**Comment by it-mak** [comment]
I apologize for the inconvenience, the containers have been rebuilt.
