### ISSUE TITLE
Missing ARM64 image for 17.0.6

### ISSUE THREAD

**Issue by rohit-tandon** [zulu-openjdk/zulu-openjdk#214]
The latest build of **jdk 17.0.6** is missing **arm64** image https://hub.docker.com/r/azul/zulu-openjdk-alpine/tags?page=1&name=17.0.6, it seems that the whole 17.0.6 is build on single arch while the previous builds were multi-arch.

**17.0.5 has arm64** in multi-arch: https://hub.docker.com/r/azul/zulu-openjdk-alpine/tags?page=1&name=17.0.5

More or less once in a month build skips arm64 images causing a lot of irritation and frustration :(

**Comment by it-mak** [comment]
The latest is [17.0.7-17.42.19](https://hub.docker.com/layers/azul/zulu-openjdk-alpine/17.0.7-17.42.19/images/sha256-a4a905c0c6cef204bd8d5d5d5fe877be92b44be9a91bf03d680fd604596e5155?context=explore)

**Comment by it-mak** [comment]
Manifest for 17.0.6 was fixed for dual arch.
