### ISSUE TITLE
Multiple statements are not allowed in default case of switch

### ISSUE THREAD

**Issue by Smainali17** [zulu-openjdk/zulu-openjdk#217]
Using zulu jdk 11 

Program - 

Public class multipleStatementsDefault {

public static boolean vowels(String vow){ 
switch(vow){
Case "a":
Case "i":
 Case "e":
Case "o":
Case "u":
System.out.println(vow + " is vowel");
break;
default: 
System.out.println(vow + " is not vowel");
return false;
 }
return true;
}

Public static void main(String args[]){
System.out.println(vowels("a"));
}
 }

Expected Output : 
a is vowel
true

Actual output: 
a is vowel
false

**Comment by AntonKozlov** [comment]
This repo is for Zulu OpenJDK. Generic java questions should be asked somewhere else, for example, on StackOverflow. Feel free to reopen, if you find this problem is specific to Zulu or e.g. a particular OpenJDK update release.
