### ISSUE TITLE
No linux/arm64 anymore for azul/zulu-openjdk:17-jre

### ISSUE THREAD

**Issue by jbuettnerbild** [zulu-openjdk/zulu-openjdk#229]
Since the last update of the image i miss the support for arm OS/ARCH.
That was definitiv the case before, because we use this image as base image since months.

I hope it was a mistake and you can push a new version with arm support asap.

https://hub.docker.com/layers/azul/zulu-openjdk/17-jre/images/sha256-ab9abc7afadf7fd20691eaa9dc0a92b7285e32113932c6784a7cc1c6ae9478ef?context=explore

**Comment by it-mak** [comment]
Thanks for the feedback, fixed. Actually were problems because of the new intermediate release.

**Comment by jbuettnerbild** [comment]
https://hub.docker.com/layers/azul/zulu-openjdk/17-jre/images/sha256-db2607c9cd1cc2b03d23a6bb849560b3b5c613e49fba89bef1f5eb9432cbdc8c?context=explore
