### ISSUE TITLE
Image tagged 11-latest no longer supports arm64 in Docker hub

### ISSUE THREAD

**Issue by yzargari** [zulu-openjdk/zulu-openjdk#231]
Hello,

We're using your docker images as base images when we build our applications. We're doing a multi-architecture build for `linux/amd64` as well as `linux/arm64`. This worked until couple days ago. I think something changed in the image published to Docker hub.

The `11-latest` image has only `linux/amd64` for architecture, while other similar images (`8-latest`, `17-latest`, etc) appear to be manifests supporting both `linux/amd64` and `linux/arm64`

Did something change with how you're publishing images or am I missing something?

Thanks!

**Comment by it-mak** [comment]
Hello, nothing changed here.
I've checked and can confirm that the 11-latest image for azul/zulu-openjdk is available on Docker Hub at the provided link:
https://hub.docker.com/layers/azul/zulu-openjdk/11-latest/images/sha256-af3ce34c4243baf072a9c3118ad516aedb683180fb30c2ba7dd34592b0dd58ec?context=explore
for both arh
