### ISSUE TITLE
Docker HUB, missing arm64/v8 image for azul/zulu-openjdk-alpine

### ISSUE THREAD

**Issue by reluxa** [zulu-openjdk/zulu-openjdk#239]
Hi, 

After a recent update in dockerhub, tag 17 does not seem to have the images for arm64/v8 platform. 

![image](https://github.com/zulu-openjdk/zulu-openjdk/assets/5830589/348eeeaf-af10-4408-84db-259dc3f328e7)

This arm64/v8 is still there for earlier tags: 

![image](https://github.com/zulu-openjdk/zulu-openjdk/assets/5830589/10456421-b33f-4cb3-9424-a9d3158cbcff)

**Comment by it-mak** [comment]
Hi, i've fixed it about half an hour. Can you recheck? 
![image](https://github.com/zulu-openjdk/zulu-openjdk/assets/26249444/1a468f05-b016-4f0f-b769-62b89e04d397)

**Comment by reluxa** [comment]
thanks for this prompt fix :)
