### ISSUE TITLE
latest azul/zulu-openjdk:8-latest not pushed as multi-arch

### ISSUE THREAD

**Issue by danbf** [zulu-openjdk/zulu-openjdk#244]
Hi,

The latest `azul/zulu-openjdk:8-latest`, https://hub.docker.com/layers/azul/zulu-openjdk/8-latest/images/sha256-52a5e97f554257c52b7264a1bc0bb3ed204f7ad263fa635325dfe5fcc9c4786e?context=explore , was not pushed as multi-arch to docker hub where I think in the past it was pushed multi-arch.

Was this intentional? If not, can we get it re-pushed as multi-arch?

![139322709-48697efa-628b-453d-b427-bd3f7cce2efc](https://github.com/zulu-openjdk/zulu-openjdk/assets/5041307/e278e595-6cf3-4a2b-a9ad-018e60fe1fbc)

Thanks
Dan

**Comment by theprotos** [comment]
Hi Dan,

The image with linux/amd64, linux/arm64/v8 is available now. Thank you for highlighting this.
