### ISSUE TITLE
POSIX locale in zulu-openjdk-centos:8u172 image

### ISSUE THREAD

**Issue by AlexStasko** [zulu-openjdk/zulu-openjdk#25]
Hi,

I've started using `zulu-openjdk-centos:8u172` image in my Jenkins as worker. But I faced an issue when I tried to build my Java app with Gradle. `javadoc` task has failed due to encoding error. As I found the issue is related to default locale of CentOS base image.
If I try to use `zulu-openjdk:8u172` everything is good. I saw that in `zulu-openjdk:8u172` image which is based on Ubuntu locale is set by `ENV` directive.

Steps to reproduce:
Run container with `zulu-openjdk-centos:8u172`
Execute `locale` inside container
Get output:
```
$> locale
LANG=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```

As far as I understand `LC_ALL` should be `en_US.UTF-8`

As workaround I set `LC_ALL` by envVars in Jenkins configuration.

Could anyone look on this and fix it if it necessary? Or put some notes about locale in CentOS based image.

Best regards,
Alex

**Comment by sgrinev** [comment]
thanks, we'll look into

**Comment by Siarhei-Yarkavy** [comment]
Is there any news? Thanks

**Comment by sgrinev** [comment]
fixed by https://github.com/zulu-openjdk/zulu-openjdk/commit/541f3c15bb60b16f8195f2c311c6c9444e63a9c2
