### ISSUE TITLE
Docker image 8-latest lost support for linux/arm64 arch

### ISSUE THREAD

**Issue by rav005** [zulu-openjdk/zulu-openjdk#256]
Been using docker image `azul/zulu-openjdk:8-latest` for while but in recent updates the 8-latest image is not available for arch arm64.

docker build command
`docker buildx build --platform linux/arm64,linux/amd64 ...`

**Comment by theprotos** [comment]
Hi [Gaurav](https://github.com/rav005),

Thank you for making us aware of the issue. We added linux/arm64,linux/amd64 to latest tags.
