### ISSUE TITLE
Docker images 8u402 versions lost support for arm64 arch

### ISSUE THREAD

**Issue by rav005** [zulu-openjdk/zulu-openjdk#260]
docker images with missing arm64 arch types

jdk 8 with tag 8u402 is LTS supported but missing arm64 arch type on images.

**Comment by theprotos** [comment]
@rav005 

Unfortunately, jdk 8 arm64 images are not ready, therefore the image tag 8u402 has only amd64. We are working on it.

**Comment by theprotos** [comment]
The images were published.
