### ISSUE TITLE
Distorless - 21-latest  - run as nonroot (65532) - no permission to write to /tmp dir

### ISSUE THREAD

**Issue by lukas-gor** [zulu-openjdk/zulu-openjdk#265]
Hi, 

just after starting spring boot application JVM crashes with `java.nio.file.AccessDeniedException: /tmp/tomcat.xxxx`. If I change to run as root `docker --user 0` everything works correctly.

**Comment by theprotos** [comment]
Hi @lukas-gor 

Cheers for identifying that issue. Azul is preparing the fix.

**Comment by theprotos** [comment]
We released updated docker images for distroless.
