### ISSUE TITLE
Upgrade Debian base image 

### ISSUE THREAD

**Issue by mdogan** [zulu-openjdk/zulu-openjdk#266]
Are you planning to upgrade base Debian image from `bullseye` to `bookworm`? Asking since bullseye will be EOL very soon..

**Comment by theprotos** [comment]
Hi @mdogan 

Thanks for flagging this for us. We are going to release new docker files this week.

**Comment by theprotos** [comment]
Done.

```
Status: Downloaded newer image for azul/zulu-openjdk-debian:22-latest
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
```

**Comment by mdogan** [comment]
- https://github.com/zulu-openjdk/zulu-openjdk/blob/master/debian/21-latest/Dockerfile
