### ISSUE TITLE
Feature request: Publish a Docker image with support for CRaC based on Java JRE

### ISSUE THREAD

**Issue by magnus-larsson** [zulu-openjdk/zulu-openjdk#277]
I'm using Azul's Docker image, `azul/zulu-openjdk:21-jdk-crac`, which contains support for CRaC. It works fine, but I would prefer a base image based on a Java JRE (instead of a JDK) for a Docker image to be used in production.

Do you plan to provide a Docker image like `azul/zulu-openjdk:21-jre-crac`?

**Comment by AntonKozlov** [comment]
The JREs with CRaC were added in #280.
