### ISSUE TITLE
OpenJDK 11?

### ISSUE THREAD

**Issue by pshirshov** [zulu-openjdk/zulu-openjdk#28]
Hi,

From what I can understand upstream didn't build `musl` version for the release.

So I'm curious if Azul is going to provide a version of OpenJDK 11 for alpine or not.

As well, `ga` version still isn't available for download, could you give me a hint where may I find any info when should it become available?

**Comment by derek-gfs** [comment]
Interested to know when Zulu OpenJDK 11 will be available from Azul (standard / Ubuntu image).

**Comment by pshirshov** [comment]
I've just switched to AdoptOpenJDK build. Works fine.
