### ISSUE TITLE
No linux/arm64 anymore for azul/zulu-openjdk:17-jre

### ISSUE THREAD

**Issue by jbuettnerbild** [zulu-openjdk/zulu-openjdk#292]
see https://github.com/zulu-openjdk/zulu-openjdk/issues/229

**Comment by igilyin** [comment]
Thank you for the report. Issue should be fixed now.

**Comment by theprotos** [comment]
Hi @jbuettnerbild,

The issue has been sorted out.

**Comment by jbuettnerbild** [comment]
thx again
