### ISSUE TITLE
Whereis the source code of zulu-openjdk ?

### ISSUE THREAD

**Issue by netroby** [zulu-openjdk/zulu-openjdk#3]
would you please release your zulu-openjdk sourcecode on github?
we want really migrate to zulu-openjdk. but want to review zulu openjdk source code first.

**Comment by sgrinev** [comment]
if you need Zulu source code you can request it following info in README file from Zulu root folder :

> For a period of three years from
> the date  of your receipt  of  this  software,  Azul  will  provide upon
> request, a complete  machine readable  copy of the  source code for such
> portions  based  on  OpenJDK on a medium  customarily used  for software
> interchange for a charge no more  than the cost of physically performing
> source distribution.
>
> Please email azul_openjdk@azulsystems.com for further information.

**Comment by mathieucaroff** [comment]
> a complete **machine readable** copy

machine readable /= human readable
