### ISSUE TITLE
Should we include that src.zip?

### ISSUE THREAD

**Issue by GoForce5500** [zulu-openjdk/zulu-openjdk#31]
We use alpine to reduce docker image size, but that src.zip is 55.1MB, which is 10X than the alpine system(4.41MB) itself.

**Comment by sgrinev** [comment]
Hi, you can opt for JRE version, added in the latest release, which is over 4 times smaller: https://github.com/zulu-openjdk/zulu-openjdk/blob/master/alpine/11-jre-latest/Dockerfile
