### ISSUE TITLE
Java 12 version of zulu-openjdk-alpine images?

### ISSUE THREAD

**Issue by pluttrell** [zulu-openjdk/zulu-openjdk#34]
Are there plans to produce a JDK/JRE 12 of the `azul/zulu-openjdk-alpin` images?

**Comment by sgrinev** [comment]
we plan to produce JDK soon

**Comment by verusikk** [comment]
OpenJDK 12 Zulu image is available now: azul/zulu-openjdk-alpine:12 java

**Comment by pluttrell** [comment]
Thank you!
