### ISSUE TITLE
Why isn't JAVA_HOME set ?

### ISSUE THREAD

**Issue by anthonydahanne** [zulu-openjdk/zulu-openjdk#37]
Hello,
I was trying out azul/zulu-openjdk:8 and then found out all other images do not have JAVA_HOME set.
Many software requires this environment variable and won't run without it being set.
Sure, I could start my containers with `--env="JAVA_HOME=/usr/lib/jvm/zulu-8-amd64/"`but why isn't it provided part of the Docker file ?
Other OpenJDK images do set it : https://github.com/docker-library/openjdk/blob/master/8/jdk/Dockerfile#L23

**Comment by sgrinev** [comment]
good point, I'll look into.

**Comment by anthonydahanne** [comment]
thanks for looking into it.
btw I've noticed it was already noticed (https://github.com/zulu-openjdk/zulu-openjdk/issues/33) but the fix (https://github.com/zulu-openjdk/zulu-openjdk/commit/8d83a01dc3cea1ec5b4cc26d648edd7c05e6d1fe) does not seem to have been published to recent Docker images (I've just tried azul/zulu-openjdk:8u202-8.36.0.1 and still without JAVA_HOME set)
