### ISSUE TITLE
Debian instead of Ubuntu?

### ISSUE THREAD

**Issue by azell** [zulu-openjdk/zulu-openjdk#4]
How difficult would it be to publish Dockerfiles with Debian base?
Is there any change needed other than changing the FROM line to debian:jessie?

**Comment by sgrinev** [comment]
Already done: https://hub.docker.com/r/azul/zulu-openjdk-debian/

**Comment by azell** [comment]
Just a small nitpick: is there a compelling bug fix or functionality to prefer wheezy over jessie?

**Comment by sgrinev** [comment]
Update is planned for next release (April CPU)

**Comment by sgrinev** [comment]
Updated to latest
