### ISSUE TITLE
publish azul/zulu-openjdk-alpine:11.0.5

### ISSUE THREAD

**Issue by pjfanning** [zulu-openjdk/zulu-openjdk#40]
Other docker images have been published for zulu 11.0.5 but azul/zulu-openjdk-alpine:11.0.5 is not yet published. Would it be possible to publish this image?

**Comment by sgrinev** [comment]
Sure, in a few days. We are preparing apk repos based images.

**Comment by dpn** [comment]
@sgrinev Any ETA on this? Thanks!

**Comment by sgrinev** [comment]
Tomorrow

**Comment by sgrinev** [comment]
done. Please, note, that new jre-headless images were added for zulu11 and 8.

**Comment by NielsDoucet** [comment]
@sgrinev This new update seems to have broken some paths in the jdk 8 images: https://github.com/zulu-openjdk/zulu-openjdk/commit/7bba55ad7fd8936b32871e55b08f6ad3e731e202
check changes in `alpine/8-jre-latest/Dockerfile`, `alpine/8-latest/Dockerfile`, `alpine/8u232-8.42.0.23-jre-headless/Dockerfile`, `alpine/8u232-8.42.0.23-jre/Dockerfile` and `alpine/8u232-8.42.0.23/Dockerfile`.
Even though they are jdk 8, they set JAVA_HOME to `/usr/lib/jvm/zulu11-ca`.
