### ISSUE TITLE
azul/zulu-openjdk-alpine 11.0.5 has broken paths

### ISSUE THREAD

**Issue by hardboiledalex** [zulu-openjdk/zulu-openjdk#42]
For example:
- for 11.0.3 ` jlink --version` gives `11.0.3`
- for 11.0.5 `jlink --version` gives `/bin/sh: jlink: not found` although the jlink itself is physically present

**Comment by sgrinev** [comment]
unfortunately, it's working as intended. Jlink was previously linked due to a "lazy" implementation of the linking w/o installer, it's not a thing java installers usually do. As a workaround, you may `export PATH=$PATH:$JAVA_HOME`.

**Comment by hardboiledalex** [comment]
Got it, thanks
