### ISSUE TITLE
Any way to get Java version before install

### ISSUE THREAD

**Issue by senthil13** [zulu-openjdk/zulu-openjdk#44]
Hi Guys,
Is there any way we can get JDK version of a zulu package before yum install ? why i am asking is the version shown by the yum info is totally different from what the jdk version is installed. for example 8.42.0.23 is equal to 8u232b18.

I know we can get the version after installing by java -version but i want to know what java version i am installing before the install. Something similar to the native openjdk install comes with OS.

```
yum info zulu-8 | grep ^Version
Version     : 8.42.0.23

yum info java-1.8.0-openjdk | grep ^Version
Version     : 1.8.0.232.b09
```

**Comment by sgrinev** [comment]
It's possible since the latest (Jan 2020) release:

`# yum info zulu-8 | grep ^Summary
Summary     : Azul Systems Zulu JDK 8.44.0.11 (8u242-b20)`

**Comment by senthil13** [comment]
@sgrinev 

After the latest update, it's not giving the version now.

```
yum info zulu-8 | grep ^Summary

# sudo yum info zulu-8 | grep ^Summary
Summary     : Transitional package for the Azul Systems Zulu JDK
```

**Comment by sgrinev** [comment]
Hi, @senthil13. Sorry my advice became obsolete. We've changed our packages structure and now you can find information you need using the next command:
`yum info zulu8 | grep ^Summary`

Note, there is no dash `zulu8`
