### ISSUE TITLE
Upgrade alpine images to use Alpine 3.11

### ISSUE THREAD

**Issue by timbru31** [zulu-openjdk/zulu-openjdk#47]
Alpine 3.11 has been released: https://alpinelinux.org/posts/Alpine-3.11.0-released.html - it would be great, if the Dockerfiles for Alpine could be updated.

**Comment by sgrinev** [comment]
Unfortunately, we need to run full verification and regression suites on the new OS before relying on it in Dockerfiles. It's currently planned for the April update.

**Comment by timbru31** [comment]
No worries, take your time. Just wanted to point out that there is an update available :)

**Comment by storem** [comment]
@sgrinev Do you have any update on this? I understand the April updates have shipped with an Alpine Linux 3.10 base.

**Comment by sgrinev** [comment]
@storem, right, we do support 3.11 now — I'll update docker images, hopefully, this week. Thanks.
