### ISSUE TITLE
gradle cannot get jdk

### ISSUE THREAD

**Issue by z0mb1ek** [zulu-openjdk/zulu-openjdk#49]
Hi. I use  azul/zulu-openjdk:13.0.2 docker image, and when I run `./gradlew bootJar --build-cache --no-daemon` gradle say that:
> ERROR: JAVA_HOME is set to an invalid directory: /usr/lib/jvm/zulu-13=13.29+9-amd64/
 Please set the JAVA_HOME variable in your environment to match the
 location of your Java installation.

13.0.1 working well

**Comment by z0mb1ek** [comment]
I see that in 13.0.1 use `ENV JAVA_HOME=/usr/lib/jvm/zulu-13-amd64/`

**Comment by jjathman** [comment]
Similar problems in at least Java 8 and Java 11 images as well.
