### ISSUE TITLE
update-ca-certificates broken on azul/zulu-openjdk-alpine:8 image

### ISSUE THREAD

**Issue by melakonda** [zulu-openjdk/zulu-openjdk#52]
When I try to install our enterprise ca certs in "azul/zulu-openjdk-alpine:8" image and command seems to be successful but curl command to https://repo.spring.io and also to our internal application is failing with cert issue which I feel when I run update-ca-certificates command its breaking something.

w/o this command "update-ca-certificates" if run only curl command to https://repo.spring.io this its working w/o any cert issue.

Following is the build which failed to run curl command

Sending build context to Docker daemon 6.216MB 
Step 1/7 : FROM azul/zulu-openjdk-alpine:8 
8: Pulling from azul/zulu-openjdk-alpine 
Digest: sha256:33e2af8c8df561b8be0201820fc2927500a9232e12d6f00f85573620fdd9d833 
Status: Image is up to date for azul/zulu-openjdk-alpine:8 
 ---> 70111b23c2c4 
Step 2/7 : USER root 
 ---> Using cache 
 ---> c210ee0cedec 
Step 3/7 : RUN set -e && env && apk --no-cache add ca-certificates curl bash net-tools perl py-pip python-dev && echo "Packages installed" 
 ---> Using cache 
 ---> bae621026c62 
Step 4/7 : COPY certs/ /usr/local/share/ca-certificates/ 
 ---> Using cache 
 ---> 976cff555ea5 
Step 5/7 : COPY ./import_geico_ca_certs.sh / 
 ---> Using cache 
 ---> cb8f5badc827 
Step 6/7 : RUN chmod 0644 /usr/local/share/ca-certificates/*.crt && chmod 755 /import_geico_ca_certs.sh && update-ca-certificates --fresh && sh /import_geico_ca_certs.sh 
 ---> Using cache 
 ---> 410b94c6e653 
Step 7/7 : RUN curl -O https://repo.spring.io/snapshot/org/springframework/cloud/spring-cloud-dataflow-shell/2.5.0.BUILD-SNAPSHOT/spring-cloud-dataflow-shell-2.5.0.BUILD-SNAPSHOT.jar && ln -s spring-cloud-dataflow-shell-2.5.0.BUILD-SNAPSHOT.jar spring-cloud-dataflow-shell.jar 
 ---> Running in 3728a7695bee 
 % Total % Received % Xferd Average Speed Time Time Time Current 
 Dload Upload Total Spent Left Speed 
 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0curl: (77) error setting certificate verify locations: 
 CAfile: /etc/ssl/certs/ca-certificates.crt 
 CApath: none 
The command '/bin/sh -c curl -O https://repo.spring.io/snapshot/org/springframework/cloud/spring-cloud-dataflow-shell/2.5.0.BUILD-SNAPSHOT/spring-cloud-dataflow-shell-2.5.0.BUILD-SNAPSHOT.jar && ln -s spring-cloud-dataflow-shell-2.5.0.BUILD-SNAPSHOT.jar spring-cloud-dataflow-shell.jar' returned a non-zero code: 77

Sending build context to Docker daemon  6.215MB
Step 1/4 : FROM azul/zulu-openjdk-alpine:8
8: Pulling from azul/zulu-openjdk-alpine
Digest: sha256:33e2af8c8df561b8be0201820fc2927500a9232e12d6f00f85573620fdd9d833
Status: Image is up to date for azul/zulu-openjdk-alpine:8
 ---> 70111b23c2c4
Step 2/4 : USER root
 ---> Using cache
 ---> c210ee0cedec
Step 3/4 : RUN set -e     && env     && apk --no-cache add         ca-certificates         curl         bash         net-tools         perl         py-pip         python-dev     && echo "Packages installed"
 ---> Using cache
 ---> bae621026c62
Step 4/4 : RUN curl -O https://repo.spring.io/snapshot/org/springframework/cloud/spring-cloud-dataflow-shell/2.5.0.BUILD-SNAPSHOT/spring-cloud-dataflow-shell-2.5.0.BUILD-SNAPSHOT.jar     && ln -s spring-cloud-dataflow-shell-2.5.0.BUILD-SNAPSHOT.jar spring-cloud-dataflow-shell.jar
 ---> Running in e4af554a244a
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 44.0M  100 44.0M    0     0   520k      0  0:01:26  0:01:26 --:--:-- 1476k
Removing intermediate container e4af554a244a
 ---> 1e3c08a616cc
Successfully built 1e3c08a616cc
Successfully tagged dtrwdc-test-lb.xxxx.net/scm/pipeline_nestpod:v1.6.8.0

**Comment by henricook** [comment]
I also have this problem, i'm unable to add custom certs to `azul/zulu-openjdk:8` by copying certs to /usr/local/share/ca-certificates then running `update-ca-certificates` - can anyone help?

**Comment by it-mak** [comment]
We have been checked, azul/zulu-openjdk:8 custom certificates are working good with using of update-ca-certificates. For alpine based images, it also works. 

`FROM azul/zulu-openjdk-alpine:8
USER root
COPY cert-alpine.pem /usr/local/share/ca-certificates/my-cert.crt
RUN apk update && apk add ca-certificates && cat /usr/local/share/ca-certificates/my-cert.crt >> /etc/ssl/certs/ca-certificates.crt && update-ca-certificates`

`Updating certificates in /etc/ssl/certs...
rehash: warning: skipping ca-certificates.crt,it does not contain exactly one certificate or CRL
rehash: warning: skipping cert-self-signed.pem,it does not contain exactly one certificate or CRL
rehash: warning: skipping duplicate certificate in cert.pem
1 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.`
