### ISSUE TITLE
8-latest is no longer available in Dockerhub

### ISSUE THREAD

**Issue by amiteswar** [zulu-openjdk/zulu-openjdk#55]
azul/zulu-openjdk-centos `8-latest` is no longer available in Dockerhub. Getting below error in my Docker build today,

```
Sending build context to Docker daemon  2.298MB
Step 1/24 : FROM azul/zulu-openjdk-centos:8-latest
manifest for azul/zulu-openjdk-centos:8-latest not found: manifest unknown: manifest unknown

```

**Comment by sgrinev** [comment]
Sorry, it was a wrongly-named tag. Please use `azul/zulu-openjdk-centos:8`

**Comment by amiteswar** [comment]
Thanks @sgrinev. Can you also confirm, if `azul/zulu-openjdk-centos:8` will always give the most latest of openjdk 8 published by azul/zulu?

**Comment by sgrinev** [comment]
Yes. All tags without specific versions are being updated every release to the latest version.

**Comment by amiteswar** [comment]
`azul/zulu-openjdk-centos:8` works, closing the issue.
