### ISSUE TITLE
'jhsdb' command not found in image taken from azul/zulu-openjdk-debian:14 

### ISSUE THREAD

**Issue by aakashhs2016** [zulu-openjdk/zulu-openjdk#57]
I upgraded an application to jdk 14 through docker using the image azul/zulu-openjdk-debian:14. But i am not able to obtain heap statistics as the container does not have jhsdb(jmap) installed. would like to know which package to install to be able to get heap statistics, run GC and take thread dumps.

**Comment by sgrinev** [comment]
Make sure you've pulled the latest version:

```
# docker pull azul/zulu-openjdk-debian:14
# docker run -it  azul/zulu-openjdk-debian:14 jmap -?
Usage:
jmap -clstats <pid>
    to connect to running process and print class loader statistics
...
```
