### ISSUE TITLE
Java security file while upgrading. 

### ISSUE THREAD

**Issue by senthil13** [zulu-openjdk/zulu-openjdk#59]
Hi Team,
We are having problem after every yum upgrade of Zulu JDK with respect to the security file. Our Siteminder policy server uses crypto policy and it will only work if that line is uncommented. After every upgrade we are doing sed commands to to enable that as the java.security files are overridden with every install.

```
sed -i 's/^#crypto.policy=/crypto.policy=/g' java.security
crypto.policy=unlimited
```

1. Is there any way to avoid updating the java security file? like passing some flags will doing `yum update` will skip the java.secutiry file update?
2. Is this approach is recomended or we have to allow rpm to override the security file and then we comment/uncomment accordingly?

Thanks
Senthil

**Comment by sgrinev** [comment]
Hi @senthil13, `crypto.policy=unlimited` is default value right now, so uncommenting it is a correct way to state that for your tools.

Unfortunately, we can't change it on our side to keep consistency with previous builds and OpenJDK.
