### ISSUE TITLE
Add support for x86_64 compact profiles

### ISSUE THREAD

**Issue by wkozaczuk** [zulu-openjdk/zulu-openjdk#6]
Hi,

Recently I created a lightweight tool to create compact profiles based on any openjdk 8 full JDK image. I was wondering if you might be interested in adding support for it: https://github.com/wkozaczuk/openjdk8_compact_profiles_builder

**Comment by mpschuetze** [comment]
Hello wkozaczuk. Thanks for the idea. Azul already has our own ability to generate compact profiles. That's actually one feature of our current Zulu Embedded commercial offering. Our internal technique also marries with our TCK testing suite, since each CP has its own test protocol. Also, it looks like you have already documented how to run against Zulu. I am not sure what more you need.--Matt

**Comment by wkozaczuk** [comment]
I was thinking you could provide Dockerfile for x86_64 docker files. 

In any case my use case involves unikernels where I was testing most minimal JRE image.

**Comment by giltene** [comment]
We have been considering adding some smaller packages (e.g. JREs and some CPs) that would actually be TCK tested, so that the resulting package will actually be Java compatible and compliant (like all our Zulu builds are). Which specific profiles do you think are interesting for public consumption?

— Gil.

On Feb 3, 2017, at 8:48 AM, WALDEMAR KOZACZUK <notifications@github.com<mailto:notifications@github.com>> wrote:


I was thinking you could provide Dockerfile for x86_64 docker files.

In any case my use case involves unikernels where I was testing most minimal JRE image.

**Comment by wkozaczuk** [comment]
I think that compact3 would be most interesting. 

Specifically many app depend log4j1.x which still depends on java.beans.* which is not part of any compact profile. Therefore the tool I created supports <<add_java_beans>> which would add java.beans.*, sun.java.beans.*, etc like so:

if [ "$JDK_ADD_JAVA_BEANS" == "add_java_beans" ]; then
  echo "Adding java/beans/* and com/sun/beans/* to lib/rt.jar, updating de-beaned classes with regular ones and updating lib/meta-index"
  jar uf $IMAGE_DIR/lib/rt.jar -C $WORKING_DIR/build/$PLATFORM_NAME/jdk/classes com/sun/beans
  jar uf $IMAGE_DIR/lib/rt.jar -C $WORKING_DIR/build/$PLATFORM_NAME/jdk/classes java/beans
  jar uf $IMAGE_DIR/lib/rt.jar -C $WORKING_DIR/build/$PLATFORM_NAME/jdk/classes java/util/logging/LogManager.class
  jar uf $IMAGE_DIR/lib/rt.jar -C $WORKING_DIR/build/$PLATFORM_NAME/jdk/classes java/util/jar/Pack200\$Packer.class
  jar uf $IMAGE_DIR/lib/rt.jar -C $WORKING_DIR/build/$PLATFORM_NAME/jdk/classes java/util/jar/Pack200\$Unpacker.class
  jar uf $IMAGE_DIR/lib/rt.jar -C $WORKING_DIR/build/$PLATFORM_NAME/jdk/classes com/sun/java/util/jar/pack/PackerImpl.class
  jar uf $IMAGE_DIR/lib/rt.jar -C $WORKING_DIR/build/$PLATFORM_NAME/jdk/classes com/sun/java/util/jar/pack/UnpackerImpl.class
  echo "com/sun/beans/" >> $IMAGE_DIR/lib/meta-index
  NEW_IMAGE_DIR=$IMAGE_BASEDIR/j2re-compact$JDK_PROFILE_NUMBER-with-java-beans-image
  mv $IMAGE_DIR $NEW_IMAGE_DIR
  IMAGE_DIR=$NEW_IMAGE_DIR
fi

For example I was able to run elasticsearch successfully on it and I think other apps would run on it as well. 

I think it would be great if you could publish compact3 + java beans JRE image.

Waldek

BTW. My main target is actually not docker but OSv unikernel ( please see https://github.com/cloudius-systems/osv and https://github.com/cloudius-systems/osv-apps to see what apps are supported) which support Java very well. I am also one of the contributors of this project focused on JVM support.

**Comment by giltene** [comment]
I don't think we can do partial mixes. And I also think they are very inadvisable things to build and propagate to others. Partial mixes like the below are specifically prohibited by the Java spec and are therefore not compatible or complaint, and will not pass TCK testing. I believe the only complaint combinations are: JDK, JRE, CP3, CP2, CP1.

— Gil.

On Feb 3, 2017, at 9:04 AM, WALDEMAR KOZACZUK <notifications@github.com<mailto:notifications@github.com>> wrote:


I think that compact3 would be most interesting.

Specifically many app depend log4j1.x which still depends on java.beans.* which is not part of any compact profile. Therefore the tool I created supports <<add_java_beans>> which would add java.beans., sun.java.beans., etc like so:

if [ "$JDK_ADD_JAVA_BEANS" == "add_java_beans" ]; then
echo "Adding java/beans/* and com/sun/beans/* to lib/rt.jar, updating de-beaned classes with regular ones and updating lib/meta-index"
jar uf $IMAGE_DIR/lib/rt.jar -C $WORKING_DIR/build/$PLATFORM_NAME/jdk/classes com/sun/beans
jar uf $IMAGE_DIR/lib/rt.jar -C $WORKING_DIR/build/$PLATFORM_NAME/jdk/classes java/beans
jar uf $IMAGE_DIR/lib/rt.jar -C $WORKING_DIR/build/$PLATFORM_NAME/jdk/classes java/util/logging/LogManager.class
jar uf $IMAGE_DIR/lib/rt.jar -C $WORKING_DIR/build/$PLATFORM_NAME/jdk/classes java/util/jar/Pack200$Packer.class
jar uf $IMAGE_DIR/lib/rt.jar -C $WORKING_DIR/build/$PLATFORM_NAME/jdk/classes java/util/jar/Pack200$Unpacker.class
jar uf $IMAGE_DIR/lib/rt.jar -C $WORKING_DIR/build/$PLATFORM_NAME/jdk/classes com/sun/java/util/jar/pack/PackerImpl.class
jar uf $IMAGE_DIR/lib/rt.jar -C $WORKING_DIR/build/$PLATFORM_NAME/jdk/classes com/sun/java/util/jar/pack/UnpackerImpl.class
echo "com/sun/beans/" >> $IMAGE_DIR/lib/meta-index
NEW_IMAGE_DIR=$IMAGE_BASEDIR/j2re-compact$JDK_PROFILE_NUMBER-with-java-beans-image
mv $IMAGE_DIR $NEW_IMAGE_DIR
IMAGE_DIR=$NEW_IMAGE_DIR
fi

For example I was able to run elasticsearch successfully on it and I think other apps would run on it as well.

I think it would be great if you could publish compact3 + java beans JRE image.

Waldek

BTW. My main target is actually not docker but OSv unikernel ( please see https://github.com/cloudius-systems/osv and https://github.com/cloudius-systems/osv-apps to see what apps are supported) which support Java very well. I am also one of the contributors of this project focused on JVM support.

**Comment by wkozaczuk** [comment]
What about plain compact3 profile?

**Comment by sgrinev** [comment]
Unfortunately, compact profiles are not planned to support.
