### ISSUE TITLE
Potential Docker hub tag issue with azul/zulu-openjdk-alpine:8

### ISSUE THREAD

**Issue by cf-sewe** [zulu-openjdk/zulu-openjdk#61]
We use the `azul/zulu-openjdk-alpine:8` tag since a while to install the Zulu JDK. 
However recently the tag behaviour changed and now it links to the JRE.

I guess this was unintentional, and would like to report this as a bug.

**Comment by cf-sewe** [comment]
@ironstas1k (azulsdrozdov?) FYI

**Comment by ironstas1k** [comment]
Thanks @cf-sewe
Looks like Alpine zulu8-jdk package installing JRE as requirements.
We will fix it ASAP
`/ # apk add zulu8-jdk
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
fetch https://repos.azul.com/zulu/alpine/x86_64/APKINDEX.tar.gz
(1/19) Installing java-common (0.2-r0)
(2/19) Installing zulu8-ca-jre-headless (8.0.252-r1)
Executing zulu8-ca-jre-headless-8.0.252-r1.post-install
(3/19) Installing zulu8-jre-headless (8.0.252-r1)
(4/19) Installing libxau (1.0.9-r0)
(5/19) Installing libbsd (0.10.0-r0)
(6/19) Installing libxdmcp (1.1.3-r0)
(7/19) Installing libxcb (1.13.1-r0)
(8/19) Installing libx11 (1.6.9-r0)
(9/19) Installing libxext (1.3.4-r0)
(10/19) Installing libxi (1.7.10-r0)
(11/19) Installing libxrender (0.9.10-r3)
(12/19) Installing libxtst (1.2.3-r3)
(13/19) Installing alsa-lib (1.2.1.2-r0)
(14/19) Installing zulu8-ca-jre (8.0.252-r1)
(15/19) Installing zulu8-jre (8.0.252-r1)
(16/19) Installing zulu8-ca-jdk-headless (8.0.252-r1)
(17/19) Installing zulu8-jdk-headless (8.0.252-r1)
(18/19) Installing zulu8-ca-jdk (8.0.252-r1)
(19/19) Installing zulu8-jdk (8.0.252-r1)
Executing busybox-1.31.1-r9.trigger
Executing java-common-0.2-r0.trigger
OK: 150 MiB in 33 packages`

**Comment by ironstas1k** [comment]
Thanks @cf-sewe 
It's okay now

```
~|⇒ docker run -it azul/zulu-openjdk-alpine:8 apk list | grep zulu
zulu8-jdk-8.0.252-r1 x86_64 {zulu8} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]
zulu8-ca-jdk-8.0.252-r1 x86_64 {zulu8-ca} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]
zulu8-jdk-headless-8.0.252-r1 x86_64 {zulu8} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]
zulu8-jre-8.0.252-r1 x86_64 {zulu8} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]
zulu8-ca-jre-headless-8.0.252-r1 x86_64 {zulu8-ca} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]
zulu8-ca-jre-8.0.252-r1 x86_64 {zulu8-ca} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]
zulu8-jre-headless-8.0.252-r1 x86_64 {zulu8} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]
zulu8-ca-jdk-headless-8.0.252-r1 x86_64 {zulu8-ca} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]
```

**Comment by cf-sewe** [comment]
Thank you, that was quick! I can confirm it is fine now.
