### ISSUE TITLE
Missing jlink command in latest 

### ISSUE THREAD

**Issue by arauchberger** [zulu-openjdk/zulu-openjdk#66]
when trying to build a minimal-java-jre:

excerpt from docker file:

``` shell
FROM azul/zulu-openjdk-alpine:11 as packager

RUN { \
    java --version ; \
    echo "jlink version:" && \
    $JAVA_HOME/bin/jlink --version ; \
    }
```

i do get 

``` shell
/bin/sh: /usr/lib/jvm/zulu11-ca/bin/jlink: not found
/ # echo $?
127
```

when i check the dir `/usr/lib/jvm/zulu11-ca/bin` i cant't find the jlink command

thanks for your assistance

AndiY

**Comment by henrist** [comment]
See #65 - try pull the newest image

**Comment by arauchberger** [comment]
i did pull the latest build/tag, but still had the same issue. NOW i pulled again - fine now
