### ISSUE TITLE
Red Hat UBI images

### ISSUE THREAD

**Issue by srbala** [zulu-openjdk/zulu-openjdk#68]
Any plans to consider Red Hat UBI based docker images?

**Comment by sgrinev** [comment]
Unfortunately, there are no plans to add RH UBI yet.

**Comment by srbala** [comment]
would you interested accepting a PR? If yes, I would like to contribute.

**Comment by giltene** [comment]
Yes.

Sent from my iPad

On Jul 18, 2020, at 6:20 AM, Bala Raman <notifications@github.com> wrote:

﻿

would you interested accepting a PR? If yes, I would like to contribute.

**Comment by sgrinev** [comment]
@srbala, sure, but please wait for the July update around next week so your contribution will be based on the latest Zulu versions.
