### ISSUE TITLE
Java packages in alpine:11.0.7 contain no files

### ISSUE THREAD

**Issue by xordspar0** [zulu-openjdk/zulu-openjdk#69]
In `azul/zulu-openjdk-alpine:11.0.7`, Java is not installed.

```
$ docker pull azul/zulu-openjdk-alpine:11.0.7
11.0.7: Pulling from azul/zulu-openjdk-alpine
Digest: sha256:1cc11a933fb817a6382bf571d2555402c28b8b2798d78e9785b27e8b9995557e
Status: Image is up to date for azul/zulu-openjdk-alpine:11.0.7
docker.io/azul/zulu-openjdk-alpine:11.0.7
$ docker run -it --rm azul/zulu-openjdk-alpine:11.0.7
/ # apk update
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
fetch https://repos.azul.com/zulu/alpine/x86_64/APKINDEX.tar.gz
v3.11.6-93-ga95c3541d2 [http://dl-cdn.alpinelinux.org/alpine/v3.11/main]
v3.11.6-94-g67535a078c [http://dl-cdn.alpinelinux.org/alpine/v3.11/community]
OK: 11463 distinct packages available
/ # javac -version
/bin/sh: javac: not found
/ # apk list --installed | grep zulu
zulu11-ca-jdk-11.0.7-r1 x86_64 {zulu11-ca} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]
zulu11-jre-11.0.7-r1 x86_64 {zulu11} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]
zulu11-ca-jdk-headless-11.0.7-r1 x86_64 {zulu11-ca} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]
zulu11-jdk-headless-11.0.7-r1 x86_64 {zulu11} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]
zulu11-jdk-11.0.7-r1 x86_64 {zulu11} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]
zulu11-ca-jre-11.0.7-r1 x86_64 {zulu11-ca} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]
zulu11-ca-jre-headless-11.0.7-r1 x86_64 {zulu11-ca} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]
zulu11-jre-headless-11.0.7-r1 x86_64 {zulu11} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]
/ # apk info -L zulu11-jdk
zulu11-jdk-11.0.7-r1 contains:

/ # apk info -L zulu11-jre
zulu11-jre-11.0.7-r1 contains:

/ #
```

**Comment by sgrinev** [comment]
1. > / # javac -version

javac and other tools are not linked by default, use `$JAVA_HOME/bin/javac` or `export PATH=$PATH:$JAVA_HOME/bin`

2. I'll check with devas about "contains:" issue

**Comment by xordspar0** [comment]
You're right, I found `java` and `javac` in `/usr/lib/jvm/zulu11-ca`, which is provided by the zulu11-ca-jre-headless. I did not expect to find the CA package. Isn't that package just supposed to contain certificates?

Do you know why this changed compared to `azul/zulu-openjdk-alpine:11.0.3`? In that version both `java` and `javac` were on the PATH.

**Comment by sgrinev** [comment]
Hi @xordspar0, `zulu11-jdk` is a meta-package for the compatibility with commercial builds. `zulu11-ca-jdk` is a proper package to check. "ca" suffix means Community Availability, not Certificate Authority, sorry for the confusion.

**Comment by sgrinev** [comment]
> Do you know why this changed compared to azul/zulu-openjdk-alpine:11.0.3? In that version both java and javac were on the PATH.

11.0.3 installation was based on the archive, directly downloaded from the website with PATH manually updated. We changed this to the proper Linux packages, which will install dependencies, support upgrading, etc. During this change, we removed direct PATH manipulation, and now only binaries properly linked from /usr/bin are available without $JAVA_HOME. 
Adding $JAVA_HOME to PATH was removed as it may affect the container's users' environments, and removing something from the PATH is way more cumbersome than adding — so we left it up to users.

**Comment by xordspar0** [comment]
> "ca" suffix means Community Availability, not Certificate Authority, sorry for the confusion.

Ok, that makes sense. I knew I must have been misunderstanding something. :smile: 

> We changed this to the proper Linux packages

I think using proper packages is an improvement. :+1: 

> removing something from the PATH is way more cumbersome than adding — so we left it up to users.

You're right, it's easy for me to add JAVA_HOME to my PATH. Thanks for helping me understand so I can fix this.

**Comment by xordspar0** [comment]
After all of this, I have one request: could you please document in the README that JAVA_HOME is no longer on the PATH after a certain version?

**Comment by it-mak** [comment]
Already present in the latest images.
