### ISSUE TITLE
azul/zulu-openjdk-debian:11 locale issue

### ISSUE THREAD

**Issue by ElvenSpellmaker** [zulu-openjdk/zulu-openjdk#71]
Currently the container is trying to use `en_US.UTF-8` which isn't present on the system and so this error appears on all container runs:
```bash
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
```

This also causes some steps which are locale dependent to fail.

**Comment by ironstas1k** [comment]
Hey folks, 
I'm assuming that we fixed this issue for January release and for further ones as well.

```
~|⇒ podman run --rm -it azul/zulu-openjdk-debian:17 locale -a
C
C.UTF-8
en_US.utf8
POSIX
```
