### ISSUE TITLE
dockerfiles based on JRE builds?

### ISSUE THREAD

**Issue by p-bakker** [zulu-openjdk/zulu-openjdk#72]
Hi,

Wondering why there are no dockerfiles based on the JRE builds of Zulu OpenJDK.

Seems like builds are provided of both JDK and JRE: https://www.azul.com/downloads/zulu-community/?version=java-14&os=alpine-linux&architecture=x86-64-bit

And I'd think that most would not need a JDK in a docker image, just a JRE, which saves more than 75% of image size

AdoptOpenJDK offers them, at least for Java 13.

I personally would love to be able to use a Alpine-based Zulu JRE 14 docker image

**Comment by EXTERNALCOREWORKS** [comment]
Hi, same thing here, any news on why starting from 8u262 and up, there is no way to pinpoint to an specific build jre using yum or dnf:
Like for instance: yum install -y zulu-8-8.44.0.11-1 was possible before, but then starting from 252, it only allows to pick I assume the latest like: yum install -y zulu8-jdk ? Thanks in advance.

**Comment by it-mak** [comment]
We have added JRE and JRE-headless images.
