### ISSUE TITLE
Centos 8.X Zulu 8u265b11 Docker file sample missing

### ISSUE THREAD

**Issue by EXTERNALCOREWORKS** [zulu-openjdk/zulu-openjdk#74]
Hi, could you please provide the corresponding Zulu 8U265b11 (zulu-8-8.48.0.53) Docker file sample ?
Also I would like it to be as before that allows to pinpoint to an specific build jre using yum or dnf:
Like for instance: yum install -y zulu-8-8.44.0.11-1 was possible before, but then starting from 252 (https://github.com/zulu-openjdk/zulu-openjdk/blob/master/centos/8u262-8.48.0.51/Dockerfile), it only allows to pick I assume the latest like: yum install -y zulu8-jdk ? 
I would like it to be something like before, i.e: yum -q -y install zulu-8-8.48.0.53-1
Thanks in advance.

**Comment by it-mak** [comment]
Please try "_yum versionlock_"
