### ISSUE TITLE
alpine headless images 11.0.7+ are not headless

### ISSUE THREAD

**Issue by nlebas** [zulu-openjdk/zulu-openjdk#75]
$ docker run --rm azul/zulu-openjdk-alpine:11.0.6-jre-headless apk list 2>&1 | grep jre
zulu11-ca-jre-headless-11.0.6-r1 x86_64 {zulu11-ca} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]
zulu11-jre-headless-11.0.6-r1 x86_64 {zulu11} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]

$ docker run --rm azul/zulu-openjdk-alpine:11.0.7-jre-headless apk list 2>&1 | grep jre
zulu11-jre-11.0.7-r1 x86_64 {zulu11} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]
zulu11-ca-jre-11.0.7-r1 x86_64 {zulu11-ca} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]
zulu11-ca-jre-headless-11.0.7-r1 x86_64 {zulu11-ca} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]
zulu11-jre-headless-11.0.7-r1 x86_64 {zulu11} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]

$ docker run --rm azul/zulu-openjdk-alpine:11.0.8-jre-headless apk list 2>&1 | grep jre
zulu11-jre-11.0.8-r1 x86_64 {zulu11} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]
zulu11-ca-jre-11.0.8-r1 x86_64 {zulu11-ca} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]
zulu11-ca-jre-headless-11.0.8-r1 x86_64 {zulu11-ca} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]
zulu11-jre-headless-11.0.8-r1 x86_64 {zulu11} (GPL-2.0-only WITH Classpath-exception-2.0) [installed]

**Comment by it-mak** [comment]
Relates to https://github.com/zulu-openjdk/zulu-openjdk/issues/160 . Closed as well, we have removed unnecessary packages from jre-headless images.
