### ISSUE TITLE
Add support for alpine

### ISSUE THREAD

**Issue by cniweb** [zulu-openjdk/zulu-openjdk#8]
Add images with apline linux (as separate tag):
https://hub.docker.com/_/alpine/

**Comment by demaniak** [comment]
This would be great! 
Ubuntu is fun and all, but "light", she is not.

**Comment by verusikk** [comment]
alpine linux with zulu is available
please, find details here: https://hub.docker.com/r/azul/zulu-openjdk-alpine/

**Comment by cniweb** [comment]
Thanks :+1:
