### ISSUE TITLE
Latest Docker images not up to date

### ISSUE THREAD

**Issue by p-bakker** [zulu-openjdk/zulu-openjdk#81]
In the Alpine section there's no 15.0.2

In the root there doesn't seem to be any Dockerfiles for Java 15 at all

The listing at https://hub.docker.com/r/azul/zulu-openjdk doesn't mention Java 15 at all

When building a Docker image today utilizing `FROM azul/zulu-openjdk-alpine:15`, we get Java version 15.0.1

On the Alpine Linux version side: we use `FROM azul/zulu-openjdk-alpine:15` as base image and it seems that today we get Alpine 3.12.1, while there's already a 3.12.3 and a 3.13.0 release (and hopefully shortly another round of releases containing the patch for https://www.zdnet.com/article/10-years-old-sudo-bug-lets-linux-users-gain-root-level-access/)

**Comment by ironstas1k** [comment]
Hi @p-bakker, thanks for heads up. 
We'v updated alpine images for previous release to 3.13, feel free to use it 
```
~|⇒ docker run -it --rm azul/zulu-openjdk-alpine:15 cat /etc/issue
Welcome to Alpine Linux 3.13
Kernel \r on an \m (\l)
```
