### ISSUE TITLE
Missing azul/zulu-openjdk-alpine 16 

### ISSUE THREAD

**Issue by mbazos** [zulu-openjdk/zulu-openjdk#85]
I noticed that with the release of JDK16 the following images repositories were updated:
azul/zulu-openjdk-centos
azul/zulu-openjdk-debian
azul/zulu-openjdk

but zul/zulu-openjdk-alpine is missing. Was just wondering if this was an oversight or there is some work happening on this.

**Comment by mbazos** [comment]
I now see that alpine has been updated with the JDK but it's now mising the 16-jre build

**Comment by ironstas1k** [comment]
Hi @mbazos, it's present now! Feel free to use it
