### ISSUE TITLE
Alpine images are using 3.13 despite those changes not being present in this repository

### ISSUE THREAD

**Issue by henricook** [zulu-openjdk/zulu-openjdk#86]
I think something might have gone wrong with the build process... or I've misunderstood something.

I pull an image with `FROM azul/zulu-openjdk-alpine:8-jre`

According to the manifests I see in this repository that should be alpine 3.12.x - but it's coming out as alpine 3.13.2... what have i missed / can you help?

**Comment by ironstas1k** [comment]
Hi @henricook, thanks for heads up. It was small disaccording between our CI/CD and GitHub repo, sorry for that!

**Comment by henricook** [comment]
@ironstas1k Thanks for this, do you know when the image will be republished?

**Comment by ironstas1k** [comment]
@henricook We'v decided to keep January Zulu release with Alpine 3.13 and not republish them. Upcoming April release will be also with 3.13

**Comment by henricook** [comment]
Ah I see, so i'm seeing loads of build problems with 3.13 that I don't see with 3.12... so I'll file separate bugs for these? :-D

**Comment by henricook** [comment]
I'm having this libfetch bug with 3.13 - basically means i can't build anything behind my proxy

https://gitlab.alpinelinux.org/alpine/aports/-/issues/11768
