### ISSUE TITLE
JDK 8 on M1 Mac does not correctly set $PATH

### ISSUE THREAD

**Issue by zanechua** [zulu-openjdk/zulu-openjdk#95]
I downloaded zulu8.54.0.21-ca-jdk8.0.292-macosx_aarch64 from https://www.azul.com/downloads/?version=java-8-lts&os=macos&architecture=arm-64-bit&package=jdk

I've tested both the DMG and ZIP. Both versions exhibit the same issue where the `PATH` variable is not pulled from the system and seems to be hard coded to `/usr/bin:/bin:/usr/sbin:/sbin`

Trying to use this to build android with gradle fails all the time for me because i need binaries that exist in `/usr/local/bin`

Trying to set the `PATH` variable at runtime with `PATH=$PATH ./gradlew` doesn't do anything either.

I downloaded JDK 11 and placed it on the system and it performs as expected with the `PATH` variable being set correctly.

**Comment by AntonKozlov** [comment]
Hi @zanechua, could you post commands and their output? Or any other way we could reproduce the issue?

**Comment by zanechua** [comment]
I'm using the jdk to build the android version of my app. I think you should be able to spin up a simple react-native project and try running the build commands and you'll hit into that error.

I debugged my adding `println System.env` to the `native_modules.gradle` file under node_modules.

I'll see if I can get some time to setup a demo project and give you instructions to reproduce them.

**Comment by zanechua** [comment]
What in the world... I was about to prepare a whole repo and what not with specific instructions on how to reproduce the problem but some how it automagically fixed itself. 

I swear it wasn't working with jdk8 and only worked with jdk11. I'm unable to reproduce it at the moment and might just be one of those quirks with the M1 Mac or something seriously else was wrong and somehow jdk11 fixed it? (I doubt it though)

Gonna close this for now as it's really weird. If I have time, i'll see if I can revisit this with perhaps a fresh OS or something.
